### ISSUE TITLE
interfaceError and assertExtension in private folder

### ISSUE THREAD

**Issue by filippeof** [mtex-toolbox/mtex#253]
Matlab -v: 2017a
Mtex -v: tested with 4.5 and 4.5.beta3
OS: MacOS 10.12.5

When trying to load EBSD data with loadEBSDang.m an error occurs when using the function assertExtension (Line 22). The function is not in the path since is located in a folder called private(interfaces/private). The catch would have to return interfaceError(fname) (line 108). However the interfaceError function is also inside the private folder. The error returned is then:

```
Undefined function 'interfaceError' for input arguments of type 'char'.

Error in loadEBSD_ang (line 108)
  interfaceError(fname);

Error in loadEBSD (line 55)
  ebsd{k} = feval(['loadEBSD_',char(interface)],...
```
Not sure if there is a reason for these files to be in a private folder but Matlab can not access folders named 'private'.
Renaming the folder to something else and adding the folder to path solved the problem.

Regards,
Filippe.

**Comment by ralfHielscher** [comment]
This is very strange. The idea of the private folders is that only the functions in the folder interfaces can access it. Maybe you have a copy of the function loadEBSD_ang at a different place?

Otherwise, if you start with a plain installation of MTEX this problem exists as well? This is hard to debug as I can not reproduce the problem.

Ralf.

**Comment by filippeof** [comment]
Thanks for clarifying, Ralf. 
I had a previous version of Mtex and probably other loadEBSD_ang file was in the path. Removing the old mtex folders and reinstalling 4.5.beta3 solved the problem. 
Thank you!
Filippe
