### ISSUE TITLE
percentage of grains parallel to {111} faces

### ISSUE THREAD

**Issue by TatVai** [mtex-toolbox/mtex#270]
Hi!

May I have a question about how to select the grains parallel to {111} faces in an orientation map?

Thank you!
TV

**Comment by kilir** [comment]
Hi TV,
please ask these kind of questions on the mailing list ( https://groups.google.com/forum/?fromgroups=#!forum/mtexmail ) because more people might be reading them.
Cheers,
Rüdiger
(PS: and if aasking in the mailing list, maybe specify what you mean by "grains paralell to {111} faces"; grain boundary traces prarallel to {111} of the grain?)
