### ISSUE TITLE
Quadruple Junctions not indentified as triple junctions

### ISSUE THREAD

**Issue by SimonJWyatt** [mtex-toolbox/mtex#398]
Hi Ralf,
I've spotted an issue with grains.triplePoints, where the junction of found grain boundaries at the same vertex isn't identified as a triple junction for any of the grains. Please find attached my expertly annotated grains.boundary map, with the triplePoints overlaid.

>ebsd = loadEBSD(fname,CS,'interface','generic','ColumnNames', { 'phi1' 'Phi' 'phi2' 'x' 'y' 'z'}, 'Bunge', 'Radians');
grains = calcGrains(ebsd,'angle',1*degree);
figure()
plot(grains.boundary)
hold on
scatter(grains.triplePoints.V(:,1),grains.triplePoints.V(:,2))

![image](https://user-images.githubusercontent.com/29143861/52295477-cedbcd00-2973-11e9-803c-c8cc094491df.png)

I expect this bug can be duplicated with a synthetic dataset of 4 1x1 grains.

Regards,

Simon

**Comment by ralfHielscher** [comment]
Should a quadrupel junction be a triple junction. I think no, because with triple junctions you habe associated several properties like the three neighboring orientations and there  misorientations which is completely different for quadruple junctions.

In there any reason why one wants to classify quadruple junctions as triple junctions?

Ralf.

**Comment by kilir** [comment]
Hi,
with respect to the physical existence of quadruple junctions, from what I've seen, those are extremely rare - but of course can geometrically exist - and actually depend much on the method of observation. If magnifications permits, most quadruple junctions turn into two triple junctions when coming closer.

From the perspective of EBSD data, obviously there might be some more quadruple junctions since we map on a finite grid. However, I would think that taking a 4-grain junction should NOT be detected as a triple junction since some applications might expect a n-by-3 answer, i.e. analysis of dihedral angles / Herring eqn. / surface energies.

Cheers,
Rüdiger

**Comment by SimonJWyatt** [comment]
Hi Ralf,

I want to measure the quadruple junction because I want to fit a Voronoi tessellation to the grain edges. grains.triplePoints are the only unique descriptors of the intersections between grains, as every pixel along the edge has its own grains.boundary. 

Without a definition of that junction, there is a void in my map where all the grains around that junction are defined by the other triple junctions which are measured. If the triplePoint needs to strictly relate 3 grains, two could be superimposed spatially to define all four grains, as long as they maintain the same rotational symmetry. If we're making the assumption that quadruple junctions are actually two triple junctions in proximity, then we can do that. But not recording them at all makes it more difficult to approximate the microstructure, and doesn't make any sense to me from an intellectual standpoint either. 

Regards, 
Simon

**Comment by ralfHielscher** [comment]
Hi Simon,

just to close this issue. The function calcGrains has now got an option ```'removeQuadruplePoints'``` to turn all quadruple junctions into triple junction. Is this helpful for you?

Ralf.
