### ISSUE TITLE
intersect function is not working properly

### ISSUE THREAD

**Issue by stefanPilz** [mtex-toolbox/mtex#415]
Hello,

thank you for your great work. 
I have recognized that the `intersect` function sometimes "overlooks" grain boundaries. I can reproduce this behavior with mtex 5.1.1 and 5.2 beta3 with smoothed and not smoothed grain boundaries. I'm using Matlab 2018b on Mac 10.14.

BR Stefan
   
![Bug intersect2](https://user-images.githubusercontent.com/47207151/57213872-62ab4c80-6fe8-11e9-9e9b-63b67efb09aa.png)

![Bug intersect3](https://user-images.githubusercontent.com/47207151/57213893-735bc280-6fe8-11e9-8f8d-846c1959aaad.png)

**Comment by ralfHielscher** [comment]
Thank you for reporting this issue. Can you reproduce this behavior using
the data sets included into MTEX or can you provide your data and code.

Thank you very much,

Ralf.


********************************************************************
Ralf Hielscher                   Tel: +371-531-38556
Fakultät für Mathematik               +371-531-22200 (Sekr.)
Technische Universität Chemnitz  Fax: +371-531-22109
Reichenhainer Str. 39            E-mail:
ralf.hielscher@mathematik.tu-chemnitz.de
D-09126 Chemnitz                 http://www.tu-chemnitz.de/~rahi
********************************************************************

**Comment by stefanPilz** [comment]
Thank you for the quick response. You can download a map together with the code here: 
https://seafile.ifw-dresden.de/f/a821e5d887634b8ea989/?dl=1

BR Stefan

**Comment by plehto** [comment]
Hi Ralf!

I am finally in the process of implementing my grain size measurement methods to work directly within MTEX. The intersect function has worked very well for this purpose, and is fast enough for even measuring every line of the ebsd map (runtime a few minutes).

I also came across this bug of the intersect bleeding through some grain boundaries. I only observed it to happen with 45 degree measurements (probably other angles too like shown by Stefan), never with horizontal and vertical measurements. 

Luckily I found this issue thread, and I'm happy to report that the implemented bugfix seems to fully take care of the issue. See the attached image.

Thanks for the excellent work Ralf =)

Best Regards,
Pauli
![intersect_bugfix](https://user-images.githubusercontent.com/32155769/98365635-5ff54180-203b-11eb-8a72-8347c0543f38.jpg)

**Comment by ralfHielscher** [comment]
Hi Pauli,

can we then expect some implementation of your method within MTEX?

All the best,

Ralf.

********************************************************************
Ralf Hielscher                   Tel: +371-531-38556
Fakultät für Mathematik               +371-531-22200 (Sekr.)
Technische Universität Chemnitz  Fax: +371-531-22109
Reichenhainer Str. 39            E-mail:
ralf.hielscher@mathematik.tu-chemnitz.de
D-09126 Chemnitz                 http://www.tu-chemnitz.de/~rahi
********************************************************************

**Comment by plehto** [comment]
Hi Ralf,

Certainly the plan is to make it open access. Probably we need to figure out in what extent it should be included in MTEX, as the full code will include quite a bit of plotting for grain size gradient etc. I started working on it only last week, and have a working beta at the moment. There are some bugs to work out so that data from different ebsd systems works reliably. In particular there are slight issues in determining the correct ebsd.id associated with the intersection points on hexagonal grid data. In these datasets (e.g. mtexdata ferrite) usually also the stepsize is not exactly as set for the acquisition. For example in the ferrite dataset the apparent ebsd.dx is 0.3 µm, but the actual value is 0.299998486722221.

At the moment I have a lookup variable for each measurement line (x, y, ebsd.id). I use the x,y output from the intersect to find the closest matching x,y coordinate, and the associated ebsd.id. To do some checking on this, is there an easy way to modify intersect.m such that it would also return the ebsd.id, or the closest ebsd.id to the intersection point? If it returned also the id, it could make for a more robust grain size measurement code.

Best Regards,
Pauli
