### ISSUE TITLE
deg2dim and dim2deg are not inverses

### ISSUE THREAD

**Issue by creuzige** [mtex-toolbox/mtex#423]
I have been playing with some of the Fourier functions to try and use these as inputs for GSAS-II.  I ran into some issues with the deg2dim and dim2deg functions, as they don't seem to be inverses.  

If you run:
>> dim2deg(84)
ans =
     3

>> deg2dim(3)
ans =
    35

Then the set.bandwidth function of FourierComponent.m (starts on line 50) the ODF components get appended with a bunch of zeros when the newLength and OldLength are compared.  (Which is what set me on this path to start)

I tried changing the while loop in dim2deg.m to a '<=' instead of a '<'.  This addressed the inversion problem, but then I got issues in FourierComponent/get.power (see below).

Index exceeds the number of array elements (84).

Error in FourierComponent/get.power (line 70)
        pow(l+1) = sum(fhat(deg2dim(l)+1:deg2dim(l+1))) ./ (2*l+1);

Using Mac OS 10.14.6, Matlab R2019A, mtex 5.0.3

**Comment by ralfHielscher** [comment]
Hi Adam,

thank you very much for reporting this issue. I hope I have fixed the issue. We still have 
```matlab
dim2deg(deg2dim(21))==20
```
but this is because MTEX uses deg2dim to determine the starting point of the the coefficients of an harmonic subspace. Maybe I will change this in the future - but for now I make use of this an to many occurrences.

Nevertheless, there was a bug in dim2deg which caused the problems you observed.

Ralf.
