### ISSUE TITLE
Error running NFFT

### ISSUE THREAD

**Issue by samjliu** [mtex-toolbox/mtex#458]
I installed MTEX on my linux desktop that is managed by our university. I got the following error message. This cause some issues when I process EBSD data. I have already tried compile the NFFT on my user folder ($HOME) with the option --with-matlab= [mymatlabpath]. I still got the same error message. Could you please help solve this? Thank you. 

OS: CentOS linux
 MATLAB Version: 9.6.0.1072779 (R2019a)
MATLAB License Number: 322847
Operating System: Linux 3.10.0-1062.12.1.el7.x86_64 #1 SMP Tue Feb 4 23:02:59 UTC 2020 x86_64
Java Version: Java 1.8.0_181-b13 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
  
MTEX: Error running NFFT!
   
  The original error message was:
  Undefined function 'nfsftmex' for input arguments of type 'char'.
 
  Try to compile the binaries or contact author for help!

**Comment by kilir** [comment]
Hi,
to use the precompiled versions you indeed need a glibc >=2.22, you probably have 2.17.
Using a newer glibc provides some nice speed improvements (since they have libmvec support) but if you are stuck to this centos version you indeed need to compile the binaries yourself.

Please provide some more details. 
What compiler options did you use?
Were there errors during compilation?
Where did you place the binaries?

Cheers,
Rüdiger
