### ISSUE TITLE
Error messages

### ISSUE THREAD

**Issue by Eddahbi** [mtex-toolbox/mtex#52]
Dear Ralf,

I measured EBSD in sample which contains two phases, the Ferrite (Fe) and martensite (Ma). I attached a CTF example. I calculated my grains using the last version 4.0.17, and I want to plot gb (Fe) whose misorientation axis form angle less than 10 degrees with x axis. For this end, I used: 
```matlab
gb = grains.boundary('Fe','Fe');
gB= grains.boundary;
ind1 = angle(gb.misorientation.axis,xvector)<10*degree;
plot(gB)
hold on
plot(Fgb(ind1),'linecolor','b','linewidth',2)
```
But I get these messages:
```
Warning: Symmetry mismatch 
> In Miller.dot at 19
  In vector3d.angle at 12 
Warning: Symmetry mismatch 
> In Miller.dot_outer at 14
  In Miller.dot at 23
  In vector3d.angle at 12
```
Similarly, I get error messages when using the expression:
```matlab
rot = rotation('axis',vector3d(1,1,1),'angle',60*degree);
ind2= angle(gb.misorientation,rot)<10*degree;
plot(gB)
hold on
plot(Fgb(ind2),'linewidth',1.5,'linecolor','b')
```
The error messages are:
```
Out of memory. Type HELP MEMORY for your
options.
Error in rotation/dot_outer (line 16)
  d = min(~i,abs(q1 * q2'));
Error in orientation/dot (line 62)
  d = max(abs(dot_outer(q,qcs)),[],2);
Error in orientation/angle (line 20)
  omega = real(2*acos(dot(o1,o2)));
```

Can you please clarify what I´m doing wrong? 
Thank you for all
Eddahbi

**Comment by ralfHielscher** [comment]
Hi Eddahbi,

I just published mtex-4.0.18 which should hopefully resolve your second issue. For the first issue I'm still thinking what to do. The point is that the misorientation axis should be given with respect to the crystal reference frame, i.e.
```matlab
ind1 = angle(gb.misorientation.axis,Miller(1,0,0,gB.CS))<10*degree;
```

I hope this helps,

Ralf.

**Comment by kilir** [comment]
Hello,
I guess the goal would be to get the misorientation axis in sample reference frame. A sort of very ugly way to do it could be:
```
gb = grains.boundary('phase','phase')
ebsd.id=[1:size(ebsd)]'  % this I needed for some reason, just can't recall why 
gbo1= ebsd.orientations(gb.ebsdId(:,1))
gbo2= ebsd.orientations(gb.ebsdId(:,2))

misor= gbo1.\gbo2;
axis_crystal = axis(misor);
misor_ax_sample = gbo1.*axis_crystal;
```
From this you can calculate the angle with for example your xvector.
All the best

**Comment by ralfHielscher** [comment]
Hi Eddahbi,

the answer of kilir is correct. You get the warning in
```matlab
ind1 = angle(gb.misorientation.axis,xvector)<10*degree;
```
since you are comparing a direction with respect to the crystal coordinate system ```gb.misorientation.axis``` with a axis with respect to the specimen coordinate system ```xvector```.
The way kilir presented to convert the misorientation axis into specimen coordinates is ok. There is a bug associated with the problem kilir accounted. Which I will fix in the next release of MTEX. Then the following syntax is recommended
```matlab
x_crystal = ebsd(inv(gB.ebsdId(:,1)).orientations) * xvector)
angle(x_crystal, gB.misOrientation.axis)
```
Going from the specimen coordinate system to the crystal reference system and computing the angle there has the advantage of taking symmetries into account.

Eddahbi, could you please add some thoughts about this. After committing the bug fix I would close the issue.

**Comment by ralfHielscher** [comment]
After a personal message from Eddahbi I realized that my previous posts are not correct. Contrary to my previous understanding the misorientation axis is well defined in specimen coordinates and not effected by crystal symmetry.

I realized that so far there is no appropriate method in MTEX to compute the misorientation axis with respect to different crystal reference frames. As a consequence I updated the function ```axis``` to work as follows
```matlab
% define a cubic and hexagonal symmetries
csCube = crystalSymmetry('cubic')
csHex = crystalSymmetry('hexagonal')

% define two orientations
o1 = orientation('euler',csCube)
o2 = orientation('euler',csHex)

% the misorientation axis with respect to the specimen coordinate system is computed by
a = axis(o1,o2)  

% the misorientation axis with respect to csCube is computed by
a = axis(inv(o2)*o1)  

% the misorientation axis with respect to csHex is computed by
a = axis(inv(o1)*o2)  
```
accordingly, for boundary misorientations, the syntax becomes
```matlab
a = axis(ebsd(gB.ebsdId(:,1)).orientations,ebsd(gB.ebsdId(:,2)).orientations)
``` 

What do you think?
Ralf.

**Comment by kilir** [comment]
Hello Ralf,
```a = axis(o1,o2) ``` would produce a vector3d instead of a Miller as it is right now. I'm happy to see this implemented because then there's no need to go through the solution above, although I'm not sure how many people expect ```axis(o1,o2)```to return a Miller in their scripts.
Would it be a good idea to think of another name, e.g. axisDirection or axisSpecimen or axisSRF or something similar?  ```grain.boundary.misorientation.axis```is misorientation axis wrt. to crystal coordinates and then there could be ```grain.boundary.misorientation.axisSRF``` for the axis wrt to the sample reference frame. 
All the best,
Rüdiger

**Comment by ralfHielscher** [comment]
Hi Rüdiger,

the point is that given the misorientation it is impossible to compute the axis with respect to the specimen coordinate system, i.e., ```grain.boundary.misorientation.axisSRF``` is not possible. The new syntax is consistent in the point that it takes always the target reference frame of an orienation / misorientation as the reference frame for the axis.

Ralf.

**Comment by kilir** [comment]
Hello Ralf, this is certainly true.
Cheers,
Rüdiger
